- name: Reset var 'my_intent'
  ansible.builtin.set_fact:
    my_intent: {}

- name: Validate l3vpn intent
  delegate_to: localhost
  ansible.utils.validate:
    data: "{{ l3vpn }}"
    criteria:
      - "{{ lookup('file', 'criteria/l3vpn.json') | from_json }}"
    engine: ansible.utils.jsonschema

- name: Crosscheck netbox
  ansible.builtin.include_tasks:
    file: netbox_l3vpn_service_check.yml
  when: netbox_discovered and not(skip_netbox | default(False) | bool)

- name: Generate low-level intent for L3VPN
  delegate_to: localhost
  ansible.builtin.set_fact:
    my_intent: "{{ lookup('template', 'transform_l3vpn_intent.j2', template_vars=intent) | from_yaml }}"
  when: l3vpn is mapping and intent is mapping

- name: Update 'network_instance' in intent
  delegate_to: localhost
  ansible.builtin.set_fact:
    intent: "{{ intent | default({}) | combine({'network_instance': my_intent.network_instance | default({}, true)}, recursive=true, list_merge='append') }}"
  when:
    - my_intent is defined and my_intent is not none
    - my_intent.network_instance is defined and my_intent.network_instance is not none

- name: Update 'subinterface' in intent
  delegate_to: localhost
  ansible.builtin.set_fact:
    intent: "{{ intent | default({}) | combine({'subinterface': my_intent.subinterface | default({}, true)}, recursive=true) }}"
  when:
    - my_intent is defined and my_intent is not none
    - my_intent.subinterface is defined and my_intent.subinterface is not none

- name: Update 'tunnel_interface' in intent
  delegate_to: localhost
  ansible.builtin.set_fact:
    intent: "{{ intent | default({}) | combine({'tunnel_interface': my_intent.tunnel_interface | default({}, true)}, recursive=true) }}"
  when:
    - my_intent is defined and my_intent is not none
    - my_intent.tunnel_interface is defined and my_intent.tunnel_interface is not none
