leaf:
  interfaces:
    ethernet-1/{1..4,10,49..50}:
      admin_state: enable
    ethernet-1/{1..4,10}:
      vlan_tagging: yes
    irb1:
    system0:
      admin_state: enable
  subinterface:
    ethernet-1/{49..50}.0:
      ipv6:
        ra: enable
        ra_min_interval: 3
  bfd:
    interfaces:
      system0.0:
        admin_state: enable
        desired_min_tx_interval: 100000
        detection_multiplier: 3
        required_min_rx_interval: 100000
      ethernet-1/{49..50}.0:
        admin_state: enable
        desired_min_tx_interval: 100000
        detection_multiplier: 3
        required_min_rx_interval: 100000
  network_instance:
    default:
      interfaces:
        - system0.0
        - ethernet-1/{49..50}.0
      autonomous-system: "{{ asn }}"
      router-id: "{{ router_id }}"
      protocols:
        bgp:
          ipv4:
            admin_state: enable
            multipath: 4
          evpn:
            admin_state: enable
            multipath: 2
          ebgp-import-reject: no
          ebgp-export-reject: no
          dynamic:
            interfaces:
              ethernet-1/49.0:
                allow-as: [ 65100 ]
                peer-group: spines
              ethernet-1/50.0:
                allow-as: [ 65100 ]
                peer-group: spines
          group:
            spines:
              description: "Peer-group for spine neighbors"
              export_policy: lo-and-servers
              enable_bfd: true
              fast_failover: true
              import_policy: pass-all
              peer_as: 65100
              ipv4:
                admin_state: enable
              epvn:
                admin_state: enable
#
spine:
  interfaces:
    ethernet-1/{1..4}:
      admin_state: enable
      _tag: isl
    system0:
      admin_state: enable
  subinterface:
    ethernet-1/{1..4}.0:
      ipv6:
        ra: enable
        ra_min_interval: 3
  bfd:
    interfaces:
      system0.0:
        admin_state: enable
        desired_min_tx_interval: 100000
        detection_multiplier: 3
        required_min_rx_interval: 100000
      ethernet-1/{1..4}.0:
        admin_state: enable
        desired_min_tx_interval: 100000
        detection_multiplier: 3
        required_min_rx_interval: 100000
  network_instance:
    default:
      interfaces:
        - system0.0
        - ethernet-1/{1..4}.0
      autonomous-system: "{{ asn }}"
      router-id: "{{ router_id }}"
      protocols:
        bgp:
          ebgp-import-reject: no
          ebgp-export-reject: no
          dynamic:
            interfaces:
              ethernet-1/1.0:
                allow-as: [ 65001 ]
                peer-group: leafs
              ethernet-1/2.0:
                allow-as: [ 65002 ]
                peer-group: leafs
              ethernet-1/3.0:
                allow-as: [ 65003 ]
                peer-group: leafs
              ethernet-1/4.0:
                allow-as: [ 65004 ]
                peer-group: leafs
          ipv4:
            admin_state: enable
            multipath: 4
          evpn:
            admin_state: enable
            multipath: 2
            rapid-update: yes
            inter-as-vpn: yes
          group:
            leafs:
              description: "Peer-group for leaf neighbors"
              enable_bfd: true
              export_policy: pass-all
              import_policy: pass-all
              ipv4:
                admin_state: enable
              epvn:
                admin_state: enable
srl:
  _features:
    auto_itf_desc: no # generate itf-desription from LLDP state
  system:
    lldp:
      admin-state: enable
    information:
      location: "Somewhere"
      contact: "John Doe"
  routing_policy:
    prefix_set:
      loopbacks:
        prefix:
          - ip-prefix: 192.168.255.0/24
            mask-length-range: "32..32"
      servers:
        prefix:
          - ip-prefix: 10.0.0.0/8
            mask-length-range: "24..32"
    policy:
      export-loopbacks:
        default-action:
          policy-result: reject
        statement:
          - name: "1"
            match:
              prefix-set: loopbacks
            action:
              policy-result: accept
      lo-and-servers:
        default-action:
          policy-result: reject
        statement:
          - name: "10"
            match:
              prefix-set: loopbacks
            action:
              policy-result: accept
          - name: "20"
            match:
              prefix-set: servers
            action:
              policy-result: accept
      pass-all:
        default-action:
          policy-result: accept
        statement:
          - name: "1"
            match:
              protocol: bgp
            action:
              policy-result: accept
      pass-evpn:
        default-action:
          policy-result: accept
        statement:
          - name: "1"
            match:
              protocol: bgp-evpn
            action:
              policy-result: accept
  acl_filters:
    ipv4-filter1:
      description: "ACL for loopbacks"
      type: ipv4 # [ipv4|ipv6|mac]
      acl-entries:
        10: # sequence number
          action: accept # [accept|drop]
          match:
            destination-ip:
              prefix: 10.0.0.0/8 
            source-ip:
              prefix: 0.0.0.0/0
            source-port:
              range: 1024..65000 # nr + '..' nr
            destination-port:
              range: 1024..65000 # nr + '..' nr
            protocol: tcp # nr or string
            icmp: 
              code: 0 # nr
              type: echo " str"
        9999:
          action: drop
    mac-filter1:
      description: "mac filter"
      type: mac
      acl-entries:
        10:
          action: accept
          match:
            destination-mac:
              address: 00:00:00:00:00:00
              mask: 00:00:00:00:00:00
            ethertype: ipv4
            source-mac:
              address: 00:00:00:00:00:00
              mask: 00:00:00:00:00:00
