- name: Reset var 'my_intent'
  delegate_to: localhost
  ansible.builtin.set_fact:
    my_intent: {}

- name: "Validate mh_access intent" 
  delegate_to: localhost
  ansible.utils.validate:
    data: "{{ mh_access }}"
    criteria:
      - "{{ lookup('file', 'criteria/mh_access.json') | from_json }}"
    engine: ansible.utils.jsonschema

- name: Generate low-level intent for mh_access
  delegate_to: localhost
  ansible.builtin.set_fact:
    my_intent: "{{ lookup('template', 'transform_mh_access_intent.j2',template_vars=intent) | from_yaml }}"
  when: mh_access is defined and mh_access is not none and intent is mapping

- name: Update 'interface' in intent
  delegate_to: localhost
  ansible.builtin.set_fact:
    intent: "{{ intent | default({}) | combine({'interfaces': my_intent.interfaces}, recursive=true) }}"
  #  when: my_intent.subinterface is defined
  when: my_intent.interfaces is defined

- name: Update 'system' in intent
  delegate_to: localhost
  ansible.builtin.set_fact:
    intent: "{{ intent | default({}) | combine({'system': my_intent.system}, recursive=true) }}"
  #  when: my_intent.subinterface is defined
  when: my_intent.system is defined
