- name: Get role path
  ansible.builtin.set_fact:
    my_dir: "{{ role_path }}"

- name: Get template version
  vars:
    calling_path: "{{ my_dir }}" # noqa: var-naming[no-role-prefix]
  ansible.builtin.include_role:
    name: utils_tpl_version

- name: Generate JSON-RPC data for /interface
  ansible.builtin.set_fact:
    update: "{{ update + lookup('template', template_file, template_vars=intent) | from_yaml | default([], true) | selectattr('operation', 'defined') | selectattr('operation', 'eq', 'update') | ansible.utils.remove_keys(target=['operation']) }}"
    replace: "{{ replace + lookup('template', template_file, template_vars=intent) | from_yaml | default([], true) | selectattr('operation', 'defined') | selectattr('operation', 'eq', 'replace') | ansible.utils.remove_keys(target=['operation']) }}"
    cacheable: true
  when: intent.interfaces is defined and intent.interfaces is not none
  vars:
    template_file: "{{ tpl_base.path + '/interface.j2' }}"

- name: Generate JSON-RPC data for /interface/subinterface
  ansible.builtin.set_fact:
    update: "{{ update + lookup('template', template_file, template_vars=intent) | from_yaml | default([], true) | selectattr('operation', 'defined') | selectattr('operation', 'eq', 'update') | ansible.utils.remove_keys(target=['operation']) }}"
    replace: "{{ replace + lookup('template', template_file, template_vars=intent) | from_yaml | default([], true) | selectattr('operation', 'defined') | selectattr('operation', 'eq', 'replace') | ansible.utils.remove_keys(target=['operation']) }}"
    cacheable: true
  when: intent.subinterface is defined and intent.subinterface is not none
  vars:
    template_file: "{{ tpl_base.path + '/subinterface.j2' }}"

- name: Generate JSON-RPC data for /tunnel-interface
  ansible.builtin.set_fact:
    update: "{{ update + lookup('template', template_file, template_vars=intent) | from_yaml | default([], true) | selectattr('operation', 'defined') | selectattr('operation', 'eq', 'update') | ansible.utils.remove_keys(target=['operation']) }}"
    replace: "{{ replace + lookup('template', template_file, template_vars=intent) | from_yaml | default([], true) | selectattr('operation', 'defined') | selectattr('operation', 'eq', 'replace') | ansible.utils.remove_keys(target=['operation']) }}"
    cacheable: true
  when: intent.tunnel_interface is defined and intent.tunnel_interface is not none
  vars:
    template_file: "{{ tpl_base.path + '/tunnel.j2' }}"
