srl:
  system:
    mtu:
      default-port-mtu: 9412
      default-l2-mtu: 9412
      default-ip-mtu: 9394
  routing_policy:
    prefix_set:
      servers:
        prefix:
          - ip-prefix: 10.0.0.0/8
            mask-length-range: "24..32"
    policy:
      export-loopbacks:
        default-action:
            policy-result: reject
        statement:
        - name: "1"
          match:
            prefix-set: loopbacks
          action:
            policy-result: accept
      lo-and-servers:
        default-action:
          policy-result: reject
        statement:
        - name: "10"
          match:
            prefix-set: loopbacks
          action:
            policy-result: accept
        - name: "20"
          match:
            prefix-set: servers
          action:
            policy-result: accept
      pass-all:
        default-action:
          policy-result: accept
        statement:
        - name: "1"
          match:
            protocol: bgp
          action:
            policy-result: accept
      pass-evpn:
        default-action:
          policy-result: accept
        statement:
        - name: "1"
          match:
            protocol: bgp-evpn
          action:
            policy-result: accept

sros:
  system:
    mtu:
      default-port-mtu: 9412
  routing_policy:
    prefix_set:
      default:
        prefix:
          - ip-prefix: 0.0.0.0/0
    community_set:
      to_dc:
        member:
          - 100:666
    policy:
      export-to-underlay:
        default-action:
          policy-result: reject
        statement:
          - name: "10"
            match:
              prefix-set: default
            action:
              policy-result: reject
          - name: "20"
            match:
              prefix-set: loopbacks
              protocol: direct
            action:
              policy-result: accept
      from_dc:
        default-action:
          policy-result: accept
        statement:
          - name: "10"
            match:
              bgp:
                community-set: "to_dc"
            action:
              policy-result: reject
      to_dc:
        default-action:
          policy-result: accept
          bgp:
            communities:
              add: "to_dc"

leaf:
  network_instance:
    default:
      protocols:
        bgp:
          group:
            overlay:
              export_policy: pass-evpn
              import_policy: pass-evpn
            spines:
              export_policy: lo-and-servers
              import_policy: pass-all

spine:
  network_instance:
    default:
      protocols:
        bgp:
          group:
            overlay:
              export_policy: pass-evpn
              import_policy: pass-evpn
            leafs:
              export_policy: pass-all
              import_policy: pass-all
            dcgws:
              export_policy: pass-all
              import_policy: pass-all

dcgw:
  network_instance:
    default:
      protocols:
        bgp:
          group:
            overlay:
              export_policy: to_dc
              import_policy: from_dc
              vpn_apply_export: true
              vpn_apply_import: true
            spines:
              export_policy: export-to-underlay
