---
# Configuration settings for network fabric
fabric:
  underlay_routing:
    bgp:
      # Flag for enabling/disabling BGP unnumbered. Needs to be false if p2p is defined.
      # bgp-unnumbered with dcgw is currently not supported!
      bgp-unnumbered: false

      # AS number range for devices within the fabric.
      # Can also be specified as a list of ranges.
      # asn:
      #   - 64601-64605
      #   - 64610-65500
      asn: 64601-65500

  # IP range for loopback interfaces
  loopback: 192.168.255.0/24

  # IP range for point-to-point links. Can also be specified as a list of CIDRs.
  # p2p:
  #   - 100.64.0.0/17
  #   - 100.64.128.0/24
  p2p: 100.64.0.0/16

  # AS number for overlay network
  overlay_asn: 65501

  # Configuration for Route Reflectors (RR)
  rr:
    # Location for RRs could be 'spine', 'external', 'borderleaf', 'superspine'
    location: 'spine'
    # List of neighbor IPs for Route Reflectors in case of 'external'
    # neighbor_list:
    #   - 1.1.1.1
    #   - 2.2.2.2

  # Spine specific configuration, defines which ports can be used for ISLs
  spine:
    clab-4l2s-s[1-2]:
      isl-ports: ethernet-1/[1-32]

  # Physical cabling layout between network devices
  fabric_cabling:
    - endpoints: ["clab-4l2s-l1:e1-50", "clab-4l2s-s1:e1-1"]
    - endpoints: ["clab-4l2s-l1:e1-49", "clab-4l2s-s2:e1-1"]
    - endpoints: ["clab-4l2s-l2:e1-50", "clab-4l2s-s1:e1-2"]
    - endpoints: ["clab-4l2s-l2:e1-49", "clab-4l2s-s2:e1-2"]
    - endpoints: ["clab-4l2s-l3:e1-50", "clab-4l2s-s1:e1-3"]
    - endpoints: ["clab-4l2s-l3:e1-49", "clab-4l2s-s2:e1-3"]
    - endpoints: ["clab-4l2s-l4:e1-50", "clab-4l2s-s1:e1-4"]
    - endpoints: ["clab-4l2s-l4:e1-49", "clab-4l2s-s2:e1-4"]

  # Override settings for specific devices
  # Overrides can be 'asn', 'loopback' or 'id'
  overrides:
    clab-4l2s-s1:
      asn: 65100
      loopback: 192.168.255.101
    clab-4l2s-s2:
      asn: 65100
      loopback: 192.168.255.102
    clab-4l2s-l1:
      asn: 65001
      loopback: 192.168.255.1
    clab-4l2s-l2:
      asn: 65002
      loopback: 192.168.255.2
    lab-4l2s-l3:
      asn: 65003
      loopback: 192.168.255.3
    clab-4l2s-l4:
      asn: 65004
      loopback: 192.168.255.4

# Sizing and capacity planning for the network fabric
# Must include all properties here
# Warning: changing any value here might lead to re-distribution of ASNs, loopback- and/or ISL-addresses!
sizing:
  max_pod: 2                  # Type: number, minimum: 0
  max_dcgw: 2                 # Type: number, minimum: 0
  max_superspine: 2           # Type: number, minimum: 0
  max_spine_in_pod: 4         # Type: number, minimum: 0, recommended minimum: 4
  max_borderleaf_in_pod: 2    # Type: number, minimum: 0
  max_leaf_in_pod: 12         # Type: number, minimum: 0, recommended minimum: 12
  max_isl_per_spine: 128      # Type: number, minimum: 0, recommended minimum: 128
  max_isl_per_dcgw: 4         # Type: number, minimum: 0
